name: cbcast-lh

dependencies:
    - liquidhaskell
    - liquid-base
    - liquid-prelude

ghc-options:
    - -Wall

library:
    source-dirs: lib
    ghc-options:
        - -fno-warn-incomplete-patterns # liquidhaskell aready does this for us
        - -fplugin=LiquidHaskell
        - -fplugin-opt=LiquidHaskell:--short-names # make errors more readable

          #        - -fplugin-opt=LiquidHaskell:--reflection # fix an error where a function taking a function-argument had an "Unbound symbol"; also necessary for extrinsic properties
          #        - -fplugin-opt=LiquidHaskell:--ple-local # enable PLE where explicitly turned on
          #        - -fplugin-opt=LiquidHaskell:--exact-data # fix an error where a function that matched a `[]` pattern had "Unbound symbol is$GHC.Types[]"
          #        - -fplugin-opt=LiquidHaskell:--exact-data-cons # make reflect able to handle functions with custom data structures
          #        - -fplugin-opt=LiquidHaskell:--no-adt # required for partial constructors

          #executables:
          #    example:
          #        main: ExampleKvServer.hs
          #        ghc-options:
          #            - -threaded
          #            - -rtsopts
          #            - -with-rtsopts=-N
          #        dependencies:
          #            - cbcast-lh
          #            - aeson
          #            - async
          #            - http-client
          #            - servant
          #            - servant-client
          #            - servant-client-core
          #            - servant-server
          #            - stm
          #            - warp
          #
          #tests:
          #    doctest:
          #        main: Doctest.hs
          #        dependencies:
          #            - doctest
          #            - QuickCheck
          #    listing:
          #        main: Listing.hs
          #        dependencies:
          #            - cbcast-lh
