resolver: lts-18.28
packages:
  - .
extra-deps:
  - rest-rewrite-0.2.0@b75893154b295e2a671278da68e2773c60a27c539a76854c86f9ae83303dea6d,3759
  - wai-middleware-metrics-0.2.4@sha256:d6b6916acd41aaef4ca59a839d40a3a377f9df784ae49fd4c64926ae916b6ba2,2890
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: b8dc0c2bdff8e6ea9ec4a9fc2439e89fdcd73b69
    subdirs:
      - .
      - liquid-base
      - liquid-ghc-prim
      - liquid-containers
      - liquid-prelude
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: d6c95d1d535125f99f382fa503d012d008b0d480
nix:
  enable: false
  packages: [ z3 zlib ]
