resolver: lts-17.2
packages:
  - .
extra-deps:
  - text-format-0.3.2
  - Diff-0.3.4
  - megaparsec-8.0.0@sha256:362f85e243ecbcb550e1de6e5c74ba5a50c09edaa1208c99bc5b9fd242227fc6,3808
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 7dc7935271ea2961398163265e6b028be3baebb4
    subdirs:
      - .
      - liquid-base
      - liquid-ghc-prim
      - liquid-containers
      - liquid-prelude
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: d34add2bb85a3edfd905acbd32cec29f55409c75
nix:
  enable: false
  packages: [ z3 ]
